package com.shanova.keyboard.emoji

/**
 * Built-in emoji catalogue. Uses platform Unicode emoji only —
 * no proprietary artwork is bundled.
 *
 * Each entry is emoji → space-separated search keywords (English).
 */
data class EmojiCategory(
    val name: String,
    val icon: String,
    val emojis: List<Pair<String, String>>
)

object EmojiData {

    val categories: List<EmojiCategory> = listOf(
        EmojiCategory(
            "Smileys", "😀",
            listOf(
                "😀" to "grin happy smile face",
                "😃" to "grin happy smile big eyes",
                "😄" to "grin happy smile eyes",
                "😁" to "beaming grin smile",
                "😆" to "laughing squinting happy",
                "😅" to "sweat smile relief",
                "🤣" to "rofl laughing rolling floor",
                "😂" to "joy tears laughing",
                "🙂" to "slight smile",
                "😉" to "wink flirt",
                "😊" to "blush smile warm",
                "😇" to "angel halo innocent",
                "🥰" to "love hearts smiling",
                "😍" to "heart eyes love",
                "🤩" to "star struck excited",
                "😘" to "kiss love",
                "😋" to "yum tasty tongue",
                "😜" to "wink tongue crazy",
                "🤪" to "zany crazy silly",
                "🤑" to "money mouth rich",
                "🤗" to "hug warm",
                "🤔" to "thinking hmm",
                "🤫" to "shush quiet secret",
                "🤐" to "zipper mouth silent",
                "😐" to "neutral meh",
                "😑" to "expressionless blank",
                "😶" to "no mouth silent",
                "😏" to "smirk",
                "😒" to "unamused annoyed",
                "🙄" to "eye roll",
                "😬" to "grimace awkward",
                "😌" to "relieved calm",
                "😔" to "pensive sad",
                "😪" to "sleepy tired",
                "😴" to "sleeping zzz",
                "😷" to "mask sick",
                "🤒" to "sick thermometer",
                "🤕" to "hurt bandage",
                "🤢" to "nauseated sick green",
                "🤧" to "sneeze cold",
                "🥵" to "hot heat sweat",
                "🥶" to "cold freezing",
                "😎" to "cool sunglasses",
                "🤓" to "nerd glasses geek",
                "🧐" to "monocle inspect",
                "😕" to "confused",
                "😟" to "worried",
                "🙁" to "frown sad",
                "😮" to "surprised open mouth",
                "😲" to "astonished shocked",
                "😳" to "flushed embarrassed",
                "🥺" to "pleading puppy eyes",
                "😢" to "cry sad tear",
                "😭" to "sob crying loudly",
                "😱" to "scream fear shocked",
                "😖" to "confounded",
                "😞" to "disappointed sad",
                "😓" to "downcast sweat",
                "😩" to "weary tired",
                "😤" to "triumph steam angry",
                "😡" to "rage angry red",
                "😠" to "angry mad",
                "🤬" to "cursing swearing symbols",
                "💀" to "skull dead",
                "💩" to "poop pile",
                "🤡" to "clown",
                "👻" to "ghost halloween",
                "👽" to "alien ufo",
                "🤖" to "robot",
                "😺" to "cat smile happy",
                "😹" to "cat joy laughing",
                "😻" to "cat heart eyes love",
                "🙈" to "see no evil monkey",
                "🙉" to "hear no evil monkey",
                "🙊" to "speak no evil monkey"
            )
        ),
        EmojiCategory(
            "People", "👋",
            listOf(
                "👋" to "wave hello hi hand",
                "🤚" to "raised back hand stop",
                "✋" to "raised hand high five",
                "🖖" to "vulcan spock",
                "👌" to "ok perfect hand",
                "🤌" to "pinched fingers italian",
                "🤏" to "pinch small little",
                "✌️" to "victory peace",
                "🤞" to "crossed fingers luck",
                "🤟" to "love you rock",
                "🤘" to "rock horns metal",
                "🤙" to "call me shaka",
                "👈" to "point left",
                "👉" to "point right",
                "👆" to "point up",
                "👇" to "point down",
                "☝️" to "index up",
                "👍" to "thumbs up like yes",
                "👎" to "thumbs down dislike no",
                "✊" to "fist raised power",
                "👊" to "fist bump punch",
                "👏" to "clap applause bravo",
                "🙌" to "raise hands celebrate hooray",
                "👐" to "open hands hug",
                "🤲" to "palms up together pray offer",
                "🤝" to "handshake deal agreement",
                "🙏" to "pray please thanks namaste",
                "💪" to "muscle strong flex biceps",
                "🦾" to "mechanical arm prosthetic",
                "👀" to "eyes look see",
                "👁️" to "eye",
                "🧠" to "brain smart",
                "🗣️" to "speak talk head",
                "👤" to "person silhouette",
                "👶" to "baby infant",
                "🧒" to "child kid",
                "👦" to "boy",
                "👧" to "girl",
                "🧑" to "person adult",
                "👨" to "man",
                "👩" to "woman",
                "🧓" to "older person elderly",
                "👴" to "old man grandpa",
                "👵" to "old woman grandma",
                "👮" to "police officer cop",
                "🕵️" to "detective spy",
                "💂" to "guard",
                "👷" to "construction worker builder",
                "🤴" to "prince",
                "👸" to "princess",
                "👳" to "turban person",
                "👲" to "person skullcap",
                "🧕" to "woman headscarf hijab",
                "🤵" to "person tuxedo",
                "👰" to "bride veil wedding",
                "🤰" to "pregnant woman",
                "🤱" to "breast feeding baby",
                "👼" to "baby angel",
                "🎅" to "santa claus christmas",
                "🤶" to "mrs claus christmas",
                "🦸" to "superhero",
                "🦹" to "supervillain",
                "🧙" to "mage wizard",
                "🧚" to "fairy",
                "🧛" to "vampire",
                "🧜" to "merperson mermaid",
                "🧝" to "elf",
                "💆" to "massage relax spa",
                "💇" to "haircut barber",
                "🚶" to "walk walking",
                "🏃" to "run running fast",
                "💃" to "dance dancing woman salsa",
                "🕺" to "dance dancing man disco",
                "👯" to "bunny ears party",
                "🧘" to "yoga meditation lotus",
                "👪" to "family",
                "👫" to "couple man woman holding hands",
                "👬" to "two men holding hands",
                "👭" to "two women holding hands",
                "💏" to "kiss couple",
                "💑" to "couple heart love"
            )
        ),
        EmojiCategory(
            "Animals", "🐶",
            listOf(
                "🐶" to "dog puppy pet",
                "🐱" to "cat kitten pet",
                "🐭" to "mouse",
                "🐹" to "hamster",
                "🐰" to "rabbit bunny",
                "🦊" to "fox",
                "🐻" to "bear",
                "🐼" to "panda",
                "🐨" to "koala",
                "🐯" to "tiger",
                "🦁" to "lion",
                "🐮" to "cow",
                "🐷" to "pig",
                "🐸" to "frog",
                "🐵" to "monkey",
                "🐔" to "chicken hen",
                "🐧" to "penguin",
                "🐦" to "bird",
                "🐤" to "chick baby bird",
                "🦆" to "duck",
                "🦅" to "eagle",
                "🦉" to "owl",
                "🦇" to "bat",
                "🐺" to "wolf",
                "🐗" to "boar",
                "🐴" to "horse",
                "🦄" to "unicorn magic",
                "🐝" to "bee honey",
                "🐛" to "bug caterpillar",
                "🦋" to "butterfly",
                "🐌" to "snail slow",
                "🐞" to "ladybug beetle",
                "🐜" to "ant",
                "🕷️" to "spider",
                "🐢" to "turtle slow",
                "🐍" to "snake",
                "🦎" to "lizard",
                "🦂" to "scorpion",
                "🐙" to "octopus",
                "🦑" to "squid",
                "🦐" to "shrimp prawn",
                "🦞" to "lobster",
                "🦀" to "crab",
                "🐡" to "blowfish pufferfish",
                "🐠" to "tropical fish",
                "🐟" to "fish",
                "🐬" to "dolphin",
                "🐳" to "whale",
                "🦈" to "shark",
                "🐊" to "crocodile alligator",
                "🐘" to "elephant",
                "🦏" to "rhino rhinoceros",
                "🦛" to "hippo hippopotamus",
                "🐪" to "camel",
                "🦒" to "giraffe",
                "🦘" to "kangaroo",
                "🐃" to "buffalo",
                "🐂" to "ox bull",
                "🐄" to "cow",
                "🐎" to "horse race",
                "🐖" to "pig",
                "🐏" to "ram sheep",
                "🐑" to "sheep ewe",
                "🦙" to "llama alpaca",
                "🐐" to "goat",
                "🦌" to "deer",
                "🐕" to "dog",
                "🐩" to "poodle dog",
                "🦚" to "peacock",
                "🦜" to "parrot",
                "🦢" to "swan",
                "🦩" to "flamingo",
                "🕊️" to "dove peace",
                "🐇" to "rabbit",
                "🦝" to "raccoon",
                "🦨" to "skunk",
                "🦡" to "badger",
                "🦦" to "otter",
                "🦥" to "sloth slow",
                "🐾" to "paw prints pet"
            )
        ),
        EmojiCategory(
            "Food", "🍕",
            listOf(
                "🍏" to "green apple fruit",
                "🍎" to "red apple fruit",
                "🍐" to "pear fruit",
                "🍊" to "orange tangerine fruit",
                "🍋" to "lemon fruit sour",
                "🍌" to "banana fruit",
                "🍉" to "watermelon fruit",
                "🍇" to "grapes fruit",
                "🍓" to "strawberry fruit berry",
                "🫐" to "blueberries berry fruit",
                "🍈" to "melon fruit",
                "🍒" to "cherries fruit",
                "🍑" to "peach fruit",
                "🥭" to "mango fruit",
                "🍍" to "pineapple fruit",
                "🥥" to "coconut",
                "🥝" to "kiwi fruit",
                "🍅" to "tomato vegetable",
                "🥑" to "avocado",
                "🥦" to "broccoli vegetable",
                "🥬" to "leafy greens vegetable",
                "🥒" to "cucumber pickle",
                "🌶️" to "chili pepper hot spicy",
                "🌽" to "corn maize",
                "🥕" to "carrot vegetable",
                "🧄" to "garlic",
                "🧅" to "onion",
                "🥔" to "potato",
                "🍠" to "sweet potato yam",
                "🥐" to "croissant bread",
                "🍞" to "bread loaf",
                "🥖" to "baguette bread",
                "🥨" to "pretzel",
                "🧀" to "cheese",
                "🥚" to "egg",
                "🍳" to "fried egg cooking",
                "🥞" to "pancakes breakfast",
                "🧇" to "waffle breakfast",
                "🥓" to "bacon",
                "🥩" to "steak meat",
                "🍗" to "chicken leg poultry",
                "🌭" to "hot dog",
                "🍔" to "burger hamburger",
                "🍟" to "fries french fries",
                "🍕" to "pizza slice",
                "🥪" to "sandwich",
                "🌮" to "taco mexican",
                "🌯" to "burrito wrap",
                "🥗" to "salad healthy",
                "🍝" to "spaghetti pasta",
                "🍜" to "ramen noodles soup",
                "🍲" to "stew pot",
                "🍛" to "curry rice",
                "🍣" to "sushi japanese",
                "🍱" to "bento box japanese",
                "🥟" to "dumpling",
                "🍤" to "fried shrimp tempura",
                "🍙" to "rice ball onigiri",
                "🍚" to "cooked rice",
                "🍥" to "fish cake narutomaki",
                "🥠" to "fortune cookie",
                "🍢" to "oden skewer",
                "🍡" to "dango",
                "🍧" to "shaved ice",
                "🍨" to "ice cream sundae",
                "🍦" to "soft ice cream cone",
                "🥧" to "pie",
                "🧁" to "cupcake",
                "🍰" to "cake shortcake",
                "🎂" to "birthday cake",
                "🍮" to "custard pudding flan",
                "🍭" to "lollipop candy",
                "🍬" to "candy sweet",
                "🍫" to "chocolate bar",
                "🍿" to "popcorn movie",
                "🍩" to "donut doughnut",
                "🍪" to "cookie",
                "🥛" to "milk glass",
                "☕" to "coffee hot drink",
                "🍵" to "tea green tea",
                "🧃" to "juice box",
                "🥤" to "cup straw soda",
                "🧋" to "bubble tea boba",
                "🍺" to "beer mug",
                "🍻" to "cheers beers",
                "🥂" to "champagne toast cheers",
                "🍷" to "wine glass",
                "🥃" to "whiskey tumbler",
                "🍸" to "cocktail martini",
                "🍹" to "tropical drink",
                "🧉" to "mate tea",
                "🍾" to "champagne bottle pop"
            )
        ),
        EmojiCategory(
            "Activities", "⚽",
            listOf(
                "⚽" to "soccer football ball",
                "🏀" to "basketball ball",
                "🏈" to "american football",
                "⚾" to "baseball",
                "🥎" to "softball",
                "🎾" to "tennis ball",
                "🏐" to "volleyball",
                "🏉" to "rugby",
                "🥏" to "frisbee disc",
                "🎱" to "billiards pool 8ball",
                "🏓" to "ping pong table tennis",
                "🏸" to "badminton",
                "🏒" to "ice hockey",
                "🥍" to "lacrosse",
                "🏏" to "cricket bat ball",
                "⛳" to "golf flag hole",
                "🏹" to "archery bow arrow",
                "🎣" to "fishing pole",
                "🥊" to "boxing glove",
                "🥋" to "martial arts karate judo",
                "🎽" to "running shirt",
                "🛹" to "skateboard",
                "🛷" to "sled",
                "⛸️" to "ice skate",
                "🥌" to "curling",
                "🎿" to "ski skis",
                "⛷️" to "skier",
                "🏂" to "snowboard",
                "🏋️" to "weightlifting gym",
                "🤼" to "wrestling",
                "🤸" to "cartwheel gymnastics",
                "⛹️" to "basketball person dribbling",
                "🤺" to "fencing",
                "🏊" to "swim swimming",
                "🏄" to "surf surfing",
                "🚣" to "rowboat rowing",
                "🧗" to "climbing",
                "🚴" to "cycling bike",
                "🏆" to "trophy win champion",
                "🥇" to "gold medal first",
                "🥈" to "silver medal second",
                "🥉" to "bronze medal third",
                "🏅" to "medal sports",
                "🎖️" to "military medal",
                "🎗️" to "remembrance ribbon",
                "🎫" to "ticket",
                "🎪" to "circus tent",
                "🤹" to "juggling",
                "🎭" to "theater drama masks",
                "🩰" to "ballet shoes",
                "🎨" to "art paint palette",
                "🎬" to "clapper movie film",
                "🎤" to "microphone sing karaoke",
                "🎧" to "headphones music",
                "🎼" to "musical score",
                "🎹" to "piano keyboard music",
                "🥁" to "drum",
                "🎷" to "saxophone jazz",
                "🎺" to "trumpet",
                "🎸" to "guitar rock",
                "🪕" to "banjo",
                "🎻" to "violin",
                "🎲" to "dice game",
                "♟️" to "chess pawn",
                "🎯" to "dart bullseye target",
                "🎳" to "bowling",
                "🎮" to "video game controller",
                "🎰" to "slot machine casino",
                "🧩" to "puzzle jigsaw"
            )
        ),
        EmojiCategory(
            "Travel", "✈️",
            listOf(
                "🚗" to "car red automobile",
                "🚕" to "taxi cab",
                "🚙" to "suv car",
                "🚌" to "bus",
                "🚎" to "trolleybus",
                "🏎️" to "race car f1",
                "🚓" to "police car",
                "🚑" to "ambulance emergency",
                "🚒" to "fire truck engine",
                "🚐" to "minibus van",
                "🚚" to "delivery truck",
                "🚛" to "truck lorry",
                "🚜" to "tractor farm",
                "🛴" to "scooter kick",
                "🚲" to "bicycle bike",
                "🛵" to "motor scooter vespa",
                "🏍️" to "motorcycle",
                "🚨" to "siren police light",
                "🚔" to "police car front",
                "🚍" to "bus front",
                "🚘" to "car front",
                "🚖" to "taxi front",
                "🚡" to "cable car",
                "🚠" to "mountain cableway",
                "🚟" to "suspension railway",
                "🚃" to "railway car train",
                "🚋" to "tram car",
                "🚞" to "mountain railway",
                "🚝" to "monorail",
                "🚄" to "bullet train fast",
                "🚅" to "bullet train",
                "🚈" to "light rail",
                "🚂" to "steam locomotive train",
                "🚆" to "train",
                "🚇" to "metro subway",
                "🚊" to "tram",
                "🚉" to "station",
                "✈️" to "airplane flight plane",
                "🛫" to "takeoff departure",
                "🛬" to "landing arrival",
                "🛩️" to "small airplane",
                "💺" to "seat airplane",
                "🚁" to "helicopter",
                "🚀" to "rocket space launch",
                "🛸" to "ufo flying saucer",
                "🛶" to "canoe kayak",
                "⛵" to "sailboat sailing",
                "🚤" to "speedboat",
                "🛥️" to "motor boat",
                "🛳️" to "cruise ship",
                "⛴️" to "ferry",
                "🚢" to "ship",
                "⚓" to "anchor ship",
                "🗺️" to "map world",
                "🗿" to "moai statue easter island",
                "🗽" to "statue of liberty new york",
                "🗼" to "tokyo tower",
                "🏰" to "castle",
                "🏯" to "japanese castle",
                "🏟️" to "stadium",
                "🎡" to "ferris wheel",
                "🎢" to "roller coaster",
                "⛲" to "fountain",
                "🏖️" to "beach umbrella vacation",
                "🏝️" to "desert island",
                "🏔️" to "snow mountain",
                "⛰️" to "mountain",
                "🌋" to "volcano",
                "🗻" to "mount fuji",
                "🏕️" to "camping tent",
                "⛺" to "tent camping",
                "🏠" to "house home",
                "🏡" to "house garden home",
                "🏢" to "office building",
                "🏥" to "hospital",
                "🏦" to "bank",
                "🏨" to "hotel",
                "🏪" to "convenience store",
                "🏫" to "school",
                "🕌" to "mosque",
                "🛕" to "hindu temple",
                "🕍" to "synagogue",
                "⛩️" to "shinto shrine",
                "🕋" to "kaaba mecca",
                "⛪" to "church",
                "🌉" to "bridge night",
                "🌃" to "city night stars"
            )
        ),
        EmojiCategory(
            "Objects", "💡",
            listOf(
                "⌚" to "watch time",
                "📱" to "phone mobile smartphone",
                "💻" to "laptop computer",
                "⌨️" to "keyboard",
                "🖥️" to "desktop computer",
                "🖨️" to "printer",
                "🖱️" to "mouse computer",
                "🕹️" to "joystick game",
                "💽" to "minidisc",
                "💾" to "floppy disk save",
                "💿" to "cd optical disk",
                "📀" to "dvd",
                "📼" to "vhs videotape",
                "📷" to "camera photo",
                "📸" to "camera flash",
                "📹" to "video camera",
                "🎥" to "movie camera",
                "📽️" to "projector film",
                "🎞️" to "film frames",
                "📞" to "telephone receiver call",
                "☎️" to "telephone",
                "📟" to "pager",
                "📠" to "fax",
                "📺" to "tv television",
                "📻" to "radio",
                "🎙️" to "studio microphone",
                "🎚️" to "level slider",
                "🎛️" to "control knobs",
                "🧭" to "compass navigation",
                "⏱️" to "stopwatch",
                "⏲️" to "timer",
                "⏰" to "alarm clock",
                "🕰️" to "mantel clock",
                "⌛" to "hourglass time",
                "⏳" to "hourglass flowing",
                "📡" to "satellite antenna",
                "🔋" to "battery charge",
                "🔌" to "electric plug",
                "💡" to "light bulb idea",
                "🔦" to "flashlight torch",
                "🕯️" to "candle",
                "🧯" to "fire extinguisher",
                "🛢️" to "oil drum",
                "💸" to "money wings",
                "💵" to "dollar money cash",
                "💴" to "yen money",
                "💶" to "euro money",
                "💷" to "pound money",
                "🪙" to "coin",
                "💰" to "money bag rich",
                "💳" to "credit card",
                "💎" to "gem diamond jewel",
                "⚖️" to "balance scale justice",
                "🪜" to "ladder",
                "🧰" to "toolbox",
                "🪛" to "screwdriver",
                "🔧" to "wrench tool",
                "🔨" to "hammer tool",
                "⚒️" to "hammer pick",
                "🛠️" to "hammer wrench tools",
                "⛏️" to "pick mining",
                "🪓" to "axe",
                "🔩" to "nut bolt",
                "⚙️" to "gear settings",
                "🧱" to "brick wall",
                "⛓️" to "chains",
                "🧲" to "magnet",
                "🔫" to "water gun pistol",
                "💣" to "bomb",
                "🧨" to "firecracker dynamite",
                "🪓" to "axe chop",
                "🔪" to "knife kitchen",
                "🗡️" to "dagger sword",
                "⚔️" to "crossed swords battle",
                "🛡️" to "shield protect",
                "🚬" to "cigarette smoking",
                "⚰️" to "coffin",
                "🪦" to "headstone grave",
                "⚱️" to "funeral urn",
                "🏺" to "amphora vase",
                "🔮" to "crystal ball fortune",
                "📿" to "prayer beads",
                "🧿" to "evil eye nazar",
                "💈" to "barber pole",
                "⚗️" to "alembic chemistry",
                "🔭" to "telescope stars",
                "🔬" to "microscope science",
                "🕳️" to "hole",
                "🩹" to "bandage adhesive",
                "🩺" to "stethoscope doctor",
                "💊" to "pill medicine",
                "💉" to "syringe vaccine injection",
                "🧬" to "dna science",
                "🦠" to "microbe virus germ",
                "🧫" to "petri dish",
                "🧪" to "test tube chemistry",
                "🌡️" to "thermometer temperature",
                "🧹" to "broom clean sweep",
                "🧺" to "basket laundry",
                "🧻" to "toilet paper roll",
                "🚽" to "toilet",
                "🚰" to "potable water tap",
                "🚿" to "shower bath",
                "🛁" to "bathtub bath",
                "🛀" to "bath person",
                "🧼" to "soap clean",
                "🪥" to "toothbrush",
                "🧽" to "sponge clean",
                "🔑" to "key lock",
                "🗝️" to "old key",
                "🚪" to "door",
                "🪑" to "chair",
                "🛋️" to "couch sofa lamp",
                "🛏️" to "bed sleep",
                "🧸" to "teddy bear toy",
                "🖼️" to "framed picture art",
                "🛍️" to "shopping bags",
                "🛒" to "shopping cart",
                "🎁" to "gift present wrapped",
                "🎈" to "balloon party",
                "🎏" to "carp streamer",
                "🎀" to "ribbon bow",
                "🎊" to "confetti party",
                "🎉" to "party popper celebrate tada",
                "🪄" to "magic wand",
                "📮" to "postbox mail",
                "📫" to "mailbox flag",
                "✉️" to "envelope mail letter",
                "📧" to "email",
                "📦" to "package box parcel",
                "🏷️" to "label tag",
                "📅" to "calendar date",
                "📈" to "chart increasing up graph",
                "📉" to "chart decreasing down",
                "📊" to "bar chart stats",
                "📋" to "clipboard",
                "📌" to "pin pushpin",
                "📍" to "round pin location",
                "📎" to "paperclip",
                "🖇️" to "linked paperclips",
                "📏" to "ruler straight",
                "📐" to "triangular ruler",
                "✂️" to "scissors cut",
                "🗃️" to "card file box",
                "🗄️" to "file cabinet",
                "🗑️" to "wastebasket trash delete",
                "🔒" to "lock locked secure",
                "🔓" to "unlock open",
                "🔏" to "lock pen",
                "🔐" to "lock key",
                "🖊️" to "pen",
                "🖋️" to "fountain pen",
                "✒️" to "black nib pen",
                "📝" to "memo pencil note write",
                "✏️" to "pencil write",
                "🔍" to "magnifying glass search",
                "🔎" to "magnifying glass right search"
            )
        ),
        EmojiCategory(
            "Symbols", "❤️",
            listOf(
                "❤️" to "red heart love",
                "🧡" to "orange heart",
                "💛" to "yellow heart",
                "💚" to "green heart",
                "💙" to "blue heart",
                "💜" to "purple heart",
                "🖤" to "black heart",
                "🤍" to "white heart",
                "🤎" to "brown heart",
                "💔" to "broken heart",
                "❣️" to "heart exclamation",
                "💕" to "two hearts love",
                "💞" to "revolving hearts",
                "💓" to "beating heart",
                "💗" to "growing heart",
                "💖" to "sparkling heart",
                "💘" to "heart arrow cupid",
                "💝" to "heart ribbon gift",
                "💟" to "heart decoration",
                "☮️" to "peace symbol",
                "✝️" to "latin cross",
                "☪️" to "star crescent islam",
                "🕉️" to "om hindu",
                "☸️" to "dharma wheel buddhism",
                "✡️" to "star of david",
                "🔯" to "six pointed star",
                "🕎" to "menorah",
                "☯️" to "yin yang",
                "☦️" to "orthodox cross",
                "🛐" to "place of worship",
                "⛎" to "ophiuchus zodiac",
                "♈" to "aries zodiac",
                "♉" to "taurus zodiac",
                "♊" to "gemini zodiac",
                "♋" to "cancer zodiac",
                "♌" to "leo zodiac",
                "♍" to "virgo zodiac",
                "♎" to "libra zodiac",
                "♏" to "scorpio zodiac",
                "♐" to "sagittarius zodiac",
                "♑" to "capricorn zodiac",
                "♒" to "aquarius zodiac",
                "♓" to "pisces zodiac",
                "🆔" to "id button",
                "⚛️" to "atom symbol science",
                "☢️" to "radioactive",
                "☣️" to "biohazard",
                "📴" to "phone off",
                "📳" to "vibration mode",
                "✅" to "check mark done correct green",
                "✔️" to "check mark heavy",
                "❌" to "cross mark wrong no",
                "❎" to "cross mark button",
                "➕" to "plus add",
                "➖" to "minus subtract",
                "➗" to "divide division",
                "✖️" to "multiply times",
                "♾️" to "infinity",
                "💲" to "dollar sign",
                "💱" to "currency exchange",
                "™️" to "trademark",
                "©️" to "copyright",
                "®️" to "registered",
                "〰️" to "wavy dash",
                "➰" to "curly loop",
                "➿" to "double curly loop",
                "🔚" to "end arrow",
                "🔙" to "back arrow",
                "🔛" to "on arrow",
                "🔝" to "top arrow",
                "🔜" to "soon arrow",
                "✳️" to "eight spoked asterisk",
                "❇️" to "sparkle",
                "‼️" to "double exclamation",
                "⁉️" to "exclamation question",
                "❓" to "question mark",
                "❔" to "white question mark",
                "❕" to "white exclamation",
                "❗" to "exclamation mark important",
                "〽️" to "part alternation",
                "⚠️" to "warning caution",
                "🚸" to "children crossing",
                "🔱" to "trident emblem",
                "⚜️" to "fleur de lis",
                "🔰" to "beginner japanese",
                "♻️" to "recycle green",
                "🔆" to "bright high brightness",
                "🔅" to "dim low brightness",
                "📶" to "signal bars",
                "🎦" to "cinema",
                "🔞" to "no under eighteen adult",
                "🚳" to "no bicycles",
                "🚭" to "no smoking",
                "🚯" to "no littering",
                "🚱" to "non potable water",
                "🚷" to "no pedestrians",
                "📵" to "no phones",
                "🔕" to "bell mute silent",
                "🔔" to "bell notification ring",
                "🎵" to "musical note",
                "🎶" to "musical notes music",
                "💤" to "zzz sleep",
                "🆒" to "cool button",
                "🆓" to "free button",
                "🆕" to "new button",
                "🆙" to "up button",
                "🆚" to "vs versus",
                "🈁" to "here japanese",
                "🈚" to "free of charge japanese",
                "🈲" to "prohibited japanese",
                "🉑" to "acceptable japanese",
                "🈸" to "application japanese",
                "🈴" to "passing grade japanese",
                "🈳" to "vacancy japanese",
                "㊗️" to "congratulations japanese",
                "㊙️" to "secret japanese",
                "🈺" to "open business japanese",
                "🈵" to "no vacancy japanese",
                "🔴" to "red circle",
                "🟠" to "orange circle",
                "🟡" to "yellow circle",
                "🟢" to "green circle",
                "🔵" to "blue circle",
                "🟣" to "purple circle",
                "⚫" to "black circle",
                "⚪" to "white circle",
                "🟤" to "brown circle",
                "🔶" to "orange diamond large",
                "🔷" to "blue diamond large",
                "🔸" to "orange diamond small",
                "🔹" to "blue diamond small",
                "🔺" to "red triangle up",
                "🔻" to "red triangle down",
                "💠" to "diamond dot",
                "🔘" to "radio button",
                "🔳" to "white square button",
                "🔲" to "black square button",
                "▶️" to "play button",
                "⏸️" to "pause button",
                "⏹️" to "stop button",
                "⏺️" to "record button",
                "⏭️" to "next track",
                "⏮️" to "previous track",
                "⏩" to "fast forward",
                "⏪" to "rewind",
                "🔀" to "shuffle",
                "🔁" to "repeat",
                "🔂" to "repeat one",
                "🔄" to "refresh counterclockwise",
                "🔃" to "clockwise arrows",
                "🎦" to "cinema film",
                "🔼" to "up button small",
                "🔽" to "down button small",
                "⏫" to "fast up",
                "⏬" to "fast down"
            )
        ),
        EmojiCategory(
            "Flags", "🏳️",
            listOf(
                "🏳️" to "white flag surrender",
                "🏴" to "black flag",
                "🏁" to "checkered flag race finish",
                "🚩" to "triangular red flag",
                "🏳️‍🌈" to "rainbow pride flag lgbt",
                "🇱🇰" to "sri lanka flag",
                "🇮🇳" to "india flag",
                "🇬🇧" to "united kingdom flag britain",
                "🇺🇸" to "united states flag america",
                "🇨🇦" to "canada flag",
                "🇦🇺" to "australia flag",
                "🇩🇪" to "germany flag",
                "🇫🇷" to "france flag",
                "🇮🇹" to "italy flag",
                "🇪🇸" to "spain flag",
                "🇯🇵" to "japan flag",
                "🇰🇷" to "south korea flag",
                "🇨🇳" to "china flag",
                "🇧🇷" to "brazil flag",
                "🇷🇺" to "russia flag",
                "🇿🇦" to "south africa flag",
                "🇦🇪" to "uae emirates flag",
                "🇸🇦" to "saudi arabia flag",
                "🇶🇦" to "qatar flag",
                "🇵🇰" to "pakistan flag",
                "🇧🇩" to "bangladesh flag",
                "🇳🇵" to "nepal flag",
                "🇲🇻" to "maldives flag",
                "🇹🇭" to "thailand flag",
                "🇮🇩" to "indonesia flag",
                "🇲🇾" to "malaysia flag",
                "🇸🇬" to "singapore flag",
                "🇵🇭" to "philippines flag",
                "🇻🇳" to "vietnam flag"
            )
        )
    )

    /** Flat list for search across all categories. */
    val all: List<Pair<String, String>> = categories.flatMap { it.emojis }

    fun search(query: String): List<Pair<String, String>> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return emptyList()
        return all.filter { (emoji, keywords) ->
            keywords.contains(q) || emoji == query.trim()
        }
    }
}
